// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns status and version information about the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Returns status and version information",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/instructors": {
            "get": {
                "description": "Retrieves a list of all instructors with their course offerings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Instructors"
                ],
                "summary": "Get all instructors",
                "responses": {
                    "200": {
                        "description": "Response for instructors",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.InstructorResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "No instructors found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/instructors/names/{name}": {
            "get": {
                "description": "Retrieves a specific instructor containing their name with all their course offerings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Instructors"
                ],
                "summary": "Get instructor by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instructor name (URL encoded)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Instructor details with offerings",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.InstructorResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Instructor not found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/instructors/{dept}": {
            "get": {
                "description": "Retrieves all instructors who teach courses in a specific department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Instructors"
                ],
                "summary": "Get instructors by department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department code (e.g., CMPT, MATH)",
                        "name": "dept",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of instructors for the department",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.InstructorResponse"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Department not found or no instructors available",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/instructors/{dept}/{number}": {
            "get": {
                "description": "Retrieves all instructors who teach a specific course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Instructors"
                ],
                "summary": "Get instructors by department and course number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department code (e.g., CMPT, MATH)",
                        "name": "dept",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course number (e.g., 120, 225)",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of instructors for the course",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.InstructorResponse"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Course not found or no instructors available",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/outlines/all": {
            "get": {
                "description": "Retrieves a paginated list of all course outlines",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outlines"
                ],
                "summary": "Get all course outlines",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items to return (pagination)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip (pagination offset)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response for course outlines",
                        "schema": {
                            "$ref": "#/definitions/model.AllCourseOutlinesResponse"
                        }
                    },
                    "404": {
                        "description": "No course outlines found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/outlines/{dept}": {
            "get": {
                "description": "Retrieves all course outlines for a specific department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outlines"
                ],
                "summary": "Get course outlines by department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department code (e.g., CMPT, MATH)",
                        "name": "dept",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of course outlines for the department",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.CourseOutline"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Department not found or no courses available",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/outlines/{dept}/{number}": {
            "get": {
                "description": "Retrieves course outline for a specific department and course number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outlines"
                ],
                "summary": "Get specific course outline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department code (e.g., CMPT, MATH)",
                        "name": "dept",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course number (e.g., 120, 225)",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Course outline details",
                        "schema": {
                            "$ref": "#/definitions/model.CourseOutline"
                        }
                    },
                    "404": {
                        "description": "Course not found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/sections/{year-term}": {
            "get": {
                "description": "Retrieves all course sections for a specific year and term",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sections"
                ],
                "summary": "Get sections by term",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Year and term in format YYYY-Term (e.g., 2024-Spring)",
                        "name": "year-term",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to include course outline data (default: false)",
                        "name": "withOutlines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of sections without outlines",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.CourseWithSectionDetails"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid year-term format or query parameters",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No sections found for the specified term",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/sections/{year-term}/{dept}": {
            "get": {
                "description": "Retrieves all course sections for a specific year, term, and department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sections"
                ],
                "summary": "Get sections by term and department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Year and term in format YYYY-Term (e.g., 2024-Spring)",
                        "name": "year-term",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Department code (e.g., CMPT, MATH)",
                        "name": "dept",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to include course outline data (default: false)",
                        "name": "withOutlines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of sections without outlines",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.CourseWithSectionDetails"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid year-term format or query parameters",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No sections found for the specified term and department",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rest/sections/{year-term}/{dept}/{number}": {
            "get": {
                "description": "Retrieves all course sections for a specific year, term, department, and course number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sections"
                ],
                "summary": "Get sections by term, department, and course number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Year and term in format YYYY-Term (e.g., 2024-Spring)",
                        "name": "year-term",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Department code (e.g., CMPT, MATH)",
                        "name": "dept",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course number (e.g., 120, 225)",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to include course outline data (default: false)",
                        "name": "withOutlines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of sections without outlines",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.CourseWithSectionDetails"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid year-term format or query parameters",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No sections found for the specified criteria",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "description": "Error information",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "main.HealthResponse": {
            "description": "Health check status information",
            "type": "object",
            "properties": {
                "lastDataUpdate": {
                    "type": "string",
                    "example": "2025-06-17T07:40:46Z"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "model.AllCourseOutlinesResponse": {
            "description": "Paginated response containing course outlines",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CourseOutline"
                    }
                },
                "next_url": {
                    "type": "string",
                    "example": "/v1/rest/outlines?limit=100\u0026offset=50"
                },
                "total_count": {
                    "type": "integer",
                    "example": 3412
                }
            }
        },
        "model.CourseOffering": {
            "description": "Course offering information for a specific term",
            "type": "object",
            "properties": {
                "instructors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "John Doe",
                        "Jane Smith"
                    ]
                },
                "term": {
                    "type": "string",
                    "example": "Fall 2024"
                }
            }
        },
        "model.CourseOutline": {
            "description": "Course outline information including general details and offerings",
            "type": "object",
            "properties": {
                "corequisites": {
                    "type": "string",
                    "example": ""
                },
                "degreeLevel": {
                    "type": "string",
                    "example": "UGRD"
                },
                "deliveryMethod": {
                    "type": "string",
                    "example": "In Person"
                },
                "dept": {
                    "type": "string",
                    "example": "CMPT"
                },
                "description": {
                    "type": "string",
                    "example": "Introduction to a variety of practical and important data structures and methods..."
                },
                "designation": {
                    "type": "string",
                    "example": "Quantitative"
                },
                "notes": {
                    "type": "string",
                    "example": ""
                },
                "number": {
                    "type": "string",
                    "example": "225"
                },
                "offerings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CourseOffering"
                    }
                },
                "prerequisites": {
                    "type": "string",
                    "example": "(MACM 101 and (CMPT 125, CMPT 129 or CMPT 135)) or (ENSC 251 and ENSC 252), all with a minimum grade of C-."
                },
                "title": {
                    "type": "string",
                    "example": "Data Structures and Programming"
                },
                "units": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "model.CourseWithSectionDetails": {
            "description": "Course with detailed section information",
            "type": "object",
            "properties": {
                "dept": {
                    "type": "string",
                    "example": "CMPT"
                },
                "number": {
                    "type": "string",
                    "example": "225"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SectionDetail"
                    }
                },
                "term": {
                    "type": "string",
                    "example": "Fall 2024"
                },
                "title": {
                    "type": "string",
                    "example": "Data Structure and Algorithms"
                },
                "units": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "model.Instructor": {
            "description": "Instructor information",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john_doe@sfu.ca"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "model.InstructorOffering": {
            "description": "Instructor offering information",
            "type": "object",
            "properties": {
                "dept": {
                    "type": "string",
                    "example": "CMPT"
                },
                "number": {
                    "type": "string",
                    "example": "225"
                },
                "term": {
                    "type": "string",
                    "example": "Fall 2024"
                },
                "title": {
                    "type": "string",
                    "example": "Data Structures and Algorithms"
                }
            }
        },
        "model.InstructorResponse": {
            "description": "Instructor information",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "offerings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.InstructorOffering"
                    }
                }
            }
        },
        "model.SectionDetail": {
            "description": "Detailed information about a course section",
            "type": "object",
            "properties": {
                "classNumber": {
                    "type": "string",
                    "example": "6327"
                },
                "deliveryMethod": {
                    "type": "string",
                    "example": "In Person"
                },
                "instructors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Instructor"
                    }
                },
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SectionSchedule"
                    }
                },
                "section": {
                    "type": "string",
                    "example": "D100"
                }
            }
        },
        "model.SectionSchedule": {
            "description": "Schedule information for a section",
            "type": "object",
            "properties": {
                "campus": {
                    "type": "string",
                    "example": "Burnaby"
                },
                "days": {
                    "type": "string",
                    "example": "Mo,We,Fr"
                },
                "endDate": {
                    "type": "string",
                    "example": "2024-12-06"
                },
                "endTime": {
                    "type": "string",
                    "example": "11:20"
                },
                "sectionCode": {
                    "type": "string",
                    "example": "LEC"
                },
                "startDate": {
                    "type": "string",
                    "example": "2024-09-03"
                },
                "startTime": {
                    "type": "string",
                    "example": "10:30"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Health endpoints for monitoring API status and availability",
            "name": "Health"
        },
        {
            "description": "Outline endpoints for retrieving course outlines, including its offerings",
            "name": "Outlines"
        },
        {
            "description": "Section endpoints for retrieving section info, including its schedules and instructor(s)",
            "name": "Sections"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "api.sfucourses.com",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "sfucourses API",
	Description:      "Unofficial API for accessing SFU course outlines, sections, and instructors robustly and used to power [sfucourses.com](https://sfucourses.com). Data is pulled from [SFU Course Outlines REST API](https://www.sfu.ca/outlines/help/api.html). This API is not affiliated with Simon Fraser University.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
